### ISSUE TITLE
NaNs in h0 in detbasis

### ISSUE THREAD

**Issue by meaganoakley** [MatthewRHermes/mrh#7]
The system here is 3 fragments of 6e,6o, and NaN's are present in h0 in the determinant basis (before transforming to CSF basis). Here is the traceback: 

Overwritten attributes  get_hcore energy_nuc get_ovlp  of <class 'pyscf.scf.hf.RHF'>
WARN: SO-CASSCF (Second order CASSCF) is an experimental feature. Its performance is bad for large systems.
Traceback (most recent call last):
  File "XX_las_3frag_66_df.py", line 119, in <module>
    energy_result = XX_dmet.doselfconsistent ()
  File "../../../mrh/my_dmet/main_object.py", line 536, in doselfconsistent
    u_diff, rdm = self.doselfconsistent_corrpot (rdm, [('corrpot', iteration)])
  File "../../../mrh/my_dmet/main_object.py", line 578, in doselfconsistent_corrpot
    orb_diff = self.doselfconsistent_orbs (lower_iters)
  File "../../../mrh/my_dmet/main_object.py", line 692, in doselfconsistent_orbs
    self.doexact (self.chempot)
  File "../../../mrh/my_dmet/main_object.py", line 280, in doexact
    frag.solve_impurity_problem (chempot_frag)
  File "../../../mrh/my_dmet/fragments.py", line 1128, in solve_impurity_problem
    self.imp_solver_function (guess_1RDM, chempot_imp)
  File "../../../mrh/my_dmet/pyscf_casscf.py", line 243, in solve
    E_CASSCF = mc.kernel(mc.mo_coeff, mc.ci)[0]
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 686, in kernel
    return mc1step.CASSCF.kernel(self, mo_coeff, ci0, callback, kernel)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/mc1step.py", line 801, in kernel
    ci0=ci0, callback=callback, verbose=self.verbose)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 484, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, fcivec, eris, log, locals())
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 696, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/casci.py", line 510, in kernel
    ecore=energy_core)
  File "../../../mrh/my_pyscf/fci/csf.py", line 519, in kernel
    idx_sym=None, ci0=ci0, **kwargs)
  File "../../../mrh/my_pyscf/fci/csf.py", line 370, in kernel
    addr, h0 = fci.pspace(h1e, eri, norb, nelec, idx_sym=idx_sym, hdiag_det=hdiag_det, hdiag_csf=hdiag_csf, npsp=max(pspace_size,nroots))
  File "../../../mrh/my_pyscf/fci/csf.py", line 509, in pspace
    econf_det_mask=self.econf_det_mask, econf_csf_mask=self.econf_csf_mask)
  File "../../../mrh/my_pyscf/fci/csf.py", line 315, in pspace
    evals_after = scipy.linalg.eigh (h0)[0]
  File "/panfs/roc/msisoft/anaconda/anaconda3_2019.10/lib/python3.7/site-packages/scipy/linalg/decomp.py", line 374, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/panfs/roc/msisoft/anaconda/anaconda3_2019.10/lib/python3.7/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "/panfs/roc/msisoft/anaconda/anaconda3_2019.10/lib/python3.7/site-packages/numpy/lib/function_base.py", line 496, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by meaganoakley** [comment]
I should also say that this happened when density fitting was turned on, where that fixed the problem last time.

**Comment by MatthewRHermes** [comment]
Meagan,

If that happened then this line should have executed before the determinant->CSF transformation:

```
        lib.logger.debug (fci, ("ERROR: h0 has {} infs, {} nans; h1e_a has {} infs, {} nans; "
            "h1e_b has {} infs, {} nans; g2e has {} infs, {} nans, norb = {}, npsp_det = {}").format (
            np.count_nonzero (np.isinf (h0)), np.count_nonzero (np.isnan (h0)),
            np.count_nonzero (np.isinf (h1e_a)), np.count_nonzero (np.isnan (h1e_a)),
            np.count_nonzero (np.isinf (h1e_b)), np.count_nonzero (np.isnan (h1e_b)),
            np.count_nonzero (np.isinf (g2e)), np.count_nonzero (np.isnan (g2e)),
            norb, npsp_det))
```

It should be in either *_hf.log or *_lasci.log (really, it should be in *_lasci.log, but I may have not set it up properly yet.)  Can you find that line of output and copy-paste it here?

**Comment by meaganoakley** [comment]
Hi Matt, 
It is printed in my frag1 output:

ERROR: h0 has 0 infs, 47200 nans; h1e_a has 0 infs, 0 nans; h1e_b has 0 infs, 0 nans; g2e has 0 infs, 1296 nans, norb = 6, npsp_det = 400

**Comment by MatthewRHermes** [comment]
OK right, I didn't pay close enough attention to the traceback but *_frag1.log is right.  

Two things:
1) Did the stdout print the line `CASSCF RHF-step energy: xxx` right before the crash?  If so, was the energy reasonable?
2) Could you sequester your debug alterations to the code?  If you're on a branch that you can keep separate from origin/dev, just do from your mrh folder:
```
git commit -a (a text editor will open and prompt you to write a commit comment; do so and write-quit to continue)
git checkout dev
git pull origin dev
```
Replace 'dev' in the second line above (but NOT the third line) with your local name for the origin/dev branch if you named it something different (like 'Matts_dev' or 'remote_dev' or something).  If you are still on your clone of the origin/dev branch, then first make a separate branch:
```
git checkout -b my_debug
```
and then do the above.  (I think we went over this stuff before but I don't remember.)

Then, using the origin/dev that you pulled, could you rerun the calculation and tell me what happens?  If I didn't make any mistakes, it should crash slightly before it crashed before, but with some additional information about the eri array that's filled with NaNs in *_frag1.log.  I'll be in soon to talk about this!

**Comment by MatthewRHermes** [comment]
There was a really goofy underdefined SVD in pyscf_casscf.py which was mixing the active orbitals basically randomly.  This might have been causing your SCF divergence problem (which apparently is what was causing those NaNs) although I'm unsure because it turns out the MO occupancies that were printed in mfmorb.molden were also unconnected to the CI vector, which in theory should have been rotated to match the randomly-reconfigured MOs (and even if they weren't, (6,6) is small enough that the in-memory diagonalizer should have been called which ought to have immediately fixed everything).  But anyway I fixed the underdefined SVD, so try `git pull origin dev` and let me know if you still have these problems.

**Comment by meaganoakley** [comment]
Hi Matt, 

I'm getting the same error as before. I looked at the orbitals and they look good - same occupation number between trial wave function and frag1 orbitals. However, it seems like it is recognizing both the trial and frag1 orbitals as 12e,12o instead of the requested 6e,6o. I have not changed the input file from previous runs, so I'm unsure what is going on here.

LASCI converged after 2 cycles before heading into frag1, and CASSCF energy looks reasonable.  

Here is the traceback: Overwritten attributes  get_hcore energy_nuc get_ovlp  of <class 'pyscf.scf.hf.RHF'>
WARN: SO-CASSCF (Second order CASSCF) is an experimental feature. Its performance is bad for large systems.
Traceback (most recent call last):
  File "c18_las_3frag_66_df.py", line 119, in <module>
    energy_result = c18_dmet.doselfconsistent ()
  File "../../../mrh/my_dmet/main_object.py", line 536, in doselfconsistent
    u_diff, rdm = self.doselfconsistent_corrpot (rdm, [('corrpot', iteration)])
  File "../../../mrh/my_dmet/main_object.py", line 578, in doselfconsistent_corrpot
    orb_diff = self.doselfconsistent_orbs (lower_iters)
  File "../../../mrh/my_dmet/main_object.py", line 692, in doselfconsistent_orbs
    self.doexact (self.chempot)
  File "../../../mrh/my_dmet/main_object.py", line 280, in doexact
    frag.solve_impurity_problem (chempot_frag)
  File "../../../mrh/my_dmet/fragments.py", line 1128, in solve_impurity_problem
    self.imp_solver_function (guess_1RDM, chempot_imp)
  File "../../../mrh/my_dmet/pyscf_casscf.py", line 241, in solve
    E_CASSCF = mc.kernel(mc.mo_coeff, mc.ci)[0]
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 686, in kernel
    return mc1step.CASSCF.kernel(self, mo_coeff, ci0, callback, kernel)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/mc1step.py", line 801, in kernel
    ci0=ci0, callback=callback, verbose=self.verbose)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 484, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, fcivec, eris, log, locals())
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/newton_casscf.py", line 696, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/casci.py", line 510, in kernel
    ecore=energy_core)
  File "../../../mrh/my_pyscf/fci/csf.py", line 520, in kernel
    idx_sym=None, ci0=ci0, **kwargs)
  File "../../../mrh/my_pyscf/fci/csf.py", line 372, in kernel
    addr, h0 = fci.pspace(h1e, eri, norb, nelec, idx_sym=idx_sym, hdiag_det=hdiag_det, hdiag_csf=hdiag_csf, npsp=max(pspace_size,nroots))
  File "../../../mrh/my_pyscf/fci/csf.py", line 510, in pspace
    econf_det_mask=self.econf_det_mask, econf_csf_mask=self.econf_csf_mask)
  File "../../../mrh/my_pyscf/fci/csf.py", line 282, in pspace
    _debug_g2e (fci, g2e, eri, norb) # Exploring g2e nan bug; remove later?
  File "../../../mrh/my_pyscf/fci/csf.py", line 233, in _debug_g2e
    raise ValueError ('g2e has {} infs and {} nans (norb = {}; shape = {})'.format (g2e_ninf, g2e_nnan, norb, g2e.shape))
ValueError: g2e has 0 infs and 1296 nans (norb = 6; shape = (6, 6, 6, 6))

in frag1.log: 
csf.pspace: Lowest-energy 200 CSFs correspond to 141 configurations which are spanned by 400 determinants
ERROR: g2e has 0 infs and 1296 nans (norb = 6; shape = (6, 6, 6, 6))
type (eri) = <class 'numpy.ndarray'>
eri.shape = (6, 6, 6, 6)
eri.dtype = float64
eri has 0 infs and 1296 nans

**Comment by MatthewRHermes** [comment]
What do you mean, (12,12)?  The traceback you printed certainly looks like it involves 6 orbitals.

Do you know what version of PySCF you're using?  The last one that I know works with mrh is conveniently labeled 1.7.0b in the changelog (commit 06a0a69d328a47ad8d1e2a4d148fb650b401d614).  If you installed PySCF from pip, then I'm afraid I don't know a good way to change that; I would recommend installing PySCF from github only.

**Comment by meaganoakley** [comment]
Hi Matt, 

When I visualize the orbitals mentioned above, I get 6 orbitals with a ~1.95 occupation and 6 orbitals with a ~0.05 occupation number, even though the computation seems to ask for the correct number of orbitals. 

I have installed pyscf from github and am using commit 7b36f4654dedcf4502f8e0ce998d99ba5762f666. I will try to use that commit and run again.

**Comment by meaganoakley** [comment]
Looks like the orbital problem went away - they look reasonable and are the 6,6 case. However, I'm still getting similar errors. Were you able to get this to run successfully?  

Overwritten attributes  get_ovlp get_hcore energy_nuc  of <class 'pyscf.scf.hf.RHF'>
Traceback (most recent call last):
  File "xx_las_3frag_66_df.py", line 119, in <module>
    energy_result = xx_dmet.doselfconsistent ()
  File "../../../mrh/my_dmet/main_object.py", line 536, in doselfconsistent
    u_diff, rdm = self.doselfconsistent_corrpot (rdm, [('corrpot', iteration)])
  File "../../../mrh/my_dmet/main_object.py", line 578, in doselfconsistent_corrpot
    orb_diff = self.doselfconsistent_orbs (lower_iters)
  File "../../../mrh/my_dmet/main_object.py", line 692, in doselfconsistent_orbs
    self.doexact (self.chempot)
  File "../../../mrh/my_dmet/main_object.py", line 280, in doexact
    frag.solve_impurity_problem (chempot_frag)
  File "../../../mrh/my_dmet/fragments.py", line 1128, in solve_impurity_problem
    self.imp_solver_function (guess_1RDM, chempot_imp)
  File "../../../mrh/my_dmet/pyscf_casscf.py", line 238, in solve
    E_CASSCF = mc.kernel(imp2mo, ci0)[0]
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/mc1step.py", line 806, in kernel
    ci0=ci0, callback=callback, verbose=self.verbose)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/mc1step.py", line 434, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, fcivec, eris, log, locals())
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/mc1step.py", line 826, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log)
  File "/panfs/roc/groups/6/gagliard/moakley/pyscf/pyscf/mcscf/casci.py", line 518, in kernel
    ecore=energy_core)
  File "../../../mrh/my_pyscf/fci/csf.py", line 520, in kernel
    idx_sym=None, ci0=ci0, **kwargs)
  File "../../../mrh/my_pyscf/fci/csf.py", line 372, in kernel
    addr, h0 = fci.pspace(h1e, eri, norb, nelec, idx_sym=idx_sym, hdiag_det=hdiag_det, hdiag_csf=hdiag_csf, npsp=max(pspace_size,nroots))
  File "../../../mrh/my_pyscf/fci/csf.py", line 510, in pspace
    econf_det_mask=self.econf_det_mask, econf_csf_mask=self.econf_csf_mask)
  File "../../../mrh/my_pyscf/fci/csf.py", line 282, in pspace
    _debug_g2e (fci, g2e, eri, norb) # Exploring g2e nan bug; remove later?
  File "../../../mrh/my_pyscf/fci/csf.py", line 233, in _debug_g2e
    raise ValueError ('g2e has {} infs and {} nans (norb = {}; shape = {})'.format (g2e_ninf, g2e_nnan, norb, g2e.shape))
ValueError: g2e has 0 infs and 144 nans (norb = 6; shape = (6, 6, 6, 6))
(ln0005)c18[1021]

**Comment by MatthewRHermes** [comment]
I've run this calculation successfully to completion 3 times now.  Trying a fourth because there was one crash that I didn't keep around because I thought it was unrelated.  It's on MSI in the folder /home/gagliard/herme068/Calculations/c18; previous successful calculations results in the subfolder s1, s2, s3; I gave the group read permissions so you should be able to see it.

Are you sure you gave me the correct c18.xyz?  The one I have is the alternating geometry.  The only other thing I can think of is if some other dependency like scipy or numpy is not up to date.

**Comment by meaganoakley** [comment]
Yes, I am certain you have the correct coordinates. Maybe tomorrow we can look at your environment and pbs script to eliminate any other potential issues.

**Comment by MatthewRHermes** [comment]
Can you check your .\_\_version\_\_ string for PySCF, numpy, and scipy?

If you don't know how to do this: get an interactive job on a compute node going on Mesabi, execute whatever commands are at the top of your pbs script (to load modules, etc.), start a python shell, and then:

```
import pyscf, numpy, scipy
print (pyscf.__version__)
print (numpy.__version__)
print (scipy.__version__)
```

When I do this, what I see is:

```
>>> print (pyscf.__version__)
1.7.0b
>>> print (numpy.__version__)
1.17.4
>>> print (scipy.__version__)
1.1.0
```

**Comment by meaganoakley** [comment]
How do you load your python? In bash? Can you tell me which version? 

I load python3/3.7.4_anaconda2019.10

```
>>> import pyscf, numpy, scipy
>>> print (pyscf.__version__)
1.7.0b
>>> print (numpy.__version__)
1.17.2
>>> print (scipy.__version__)
1.3.1
```

**Comment by MatthewRHermes** [comment]
Yes, I just type "python" in the bash terminal to start an interactive interpreter shell.  I'm using python 3.6.6 with conda version 4.5.12.  It looks like your python and scipy are slightly higher-version than mine, whereas your numpy is very slightly lower.  I updated scipy to your version and resubmitted; it seems to still be running to completion.  Now I'm updating python to your version.
